name: drupal-project

config:
  php: "8.1"
  via: nginx
  webroot: web
  database: "mariadb:10.3"
  composer_version: 2
  xdebug: off
  config:
    php: .lando/core/php.ini
    database: .lando/core/my.cnf

tooling:
  composer:
    description: "Runs Composer commands"
    cmd:
      - appserver: /usr/local/bin/composer
  grumphp:
    description: "Runs grumphp commands"
    cmd:
      - appserver: ./vendor/bin/grumphp
  phpunit:
    description: "Runs PHPUnit commands"
    user: www-data
    cmd:
      - appserver: "/app/.lando/core/_run-scripts.sh tooling-phpunit.sh"
  regenerate-phpunit-config:
    description: "Regenerates fresh PHPUnit configuration."
    cmd:
      - appserver: "/app/.lando/core/_run-scripts.sh tooling-regenerate-phpunit-config.sh"
  varnishadm:
    description: "Runs varnishadm commands"
    service: varnish
    user: root
  xdebug:
    description: "Loads Xdebug in the selected mode"
    cmd:
      - appserver: "/app/.lando/core/_run-scripts.sh tooling-xdebug.sh"
    user: root
  load-wunderio-lando-drupal-extensions:
    description: "Helper to add extension under wunderio:extensions: in your .lando.yml. You need 'lando rebuild' for the changes to take affect."
    cmd:
      - appserver: "/app/vendor/wunderio/lando-drupal/scripts/load_extensions.sh"
  unload-wunderio-lando-drupal-extensions:
    description: "Helper to remove extension under wunderio:extensions: in your .lando.yml. You need 'lando rebuild' for the changes to take affect."
    cmd:
      - appserver: "/app/vendor/wunderio/lando-drupal/scripts/unload_extensions.sh"

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
      - "/app/.lando/core/_run-scripts.sh services-adminer-run-as-root.sh"
  appserver:
    build_as_root:
      - "/app/.lando/core/_run-scripts.sh services-appserver-build-as-root.sh"
    # Install dependencies when building lando.
    build:
      - "/app/.lando/core/_run-scripts.sh services-appserver-build.sh"
    run_as_root:
      - "/app/.lando/core/_run-scripts.sh services-appserver-run-as-root.sh"
    run:
      - "/app/.lando/core/_run-scripts.sh services-appserver-run.sh"
    # Uncomment this if you need to edit files inside the container
    #build_as_root:
    #  - apt update -y
    #  - apt install vim -y
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: lando
        VARNISH_ADMIN_HOST: varnish
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        PHP_IDE_CONFIG: serverName=appserver
        # PHPUnit settings. @see: .lando/core/phpunit.sh
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
  chrome:
    type: compose
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  # Use random static high port for database connection.
  # @see: https://docs.lando.dev/guides/external-access.html
  # database:
  #   portforward: 34567
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  # varnish:
  #   type: "varnish:6"
  #   backends:
  #     - appserver_nginx
  #   config:
  #     vcl: .lando/core/varnish.vcl
  #   ssl: true
  #   overrides:
  #     environment:
  #       ADMIN_PORT: ":6082"
  #       VARNISH_ALLOW_UNRESTRICTED_PURGE: "true"

proxy:
  adminer:
    - adminer.drupal-project.lndo.site
  mailhog:
    - mail.lndo.site
  # varnish:
  #   - varnish.drupal-project.lndo.site

events:
  post-db-import:
    - appserver: "cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login"
  pre-rebuild:
    - appserver: "SCRIPT=/app/vendor/wunderio/lando-drupal/scripts/load_extensions.sh && [ -f \"$SCRIPT\" ] && bash \"$SCRIPT\" || true"

env_file:
  - .lando/core/.env
  - .lando/custom/.env

# Tested with Lando version
version: v3.18.0
